import os
import random
import dodecaphony
from enum import Enum


class Variations(Enum):
    SERIES = 0
    INVERSE = 1
    RETROGRADE = 2
    RETROGRADEINVERSE = 3


class VoiceTypes(Enum):
    SOPRANO = 1
    MEZZOSOPRANO = 2
    ALTO = 3
    TENOR = 4
    BARITONE = 5
    BASS = 6


class ScoreGenerator:
    def __init__(self, dodec: dodecaphony.Dodecaphony):
        self._dodec = dodec
        self._composition = ""
        self._score = ""
        self._lengths = [16, 24, 8, 12, 4, 6, 2, 3, 1, 16, 24, 8, 12, 4, 6, 2, 3, 1]  # Ordered from longest to shortest - counted in 16ths
        self._range = range(18)
        self._chances = list(self._dodec.note_chances.values()) + list(self._dodec.rest_chances.values())  # Same order as lengths

    def generate_repeat(self, series, voice_type):
        series_repeat = ""
        counter = 0
        # Keep adding notes/rests until one series is complete.
        # Keep track of the note range to make sure that the line stays within the boundaries.
        # Decide whether to add a note or a rest
        while counter < 12:
            next_type = random.choices(self._range, self._chances)
            if next_type[0] < 9:  # Note
                series_repeat += series[counter]
                counter += 1
            else:  # Rest
                series_repeat += "r"
            series_repeat += str(self._lengths[next_type[0]])
            series_repeat += " "
        return series_repeat


    def create_voice_preamble(self, voice):
        preamble = ""
        if voice in range(1, 4):  # G clef
            preamble += "\n\\new Staff = \""
            if voice == 1:
                preamble += "Soprano\" "
            elif voice == 2:
                preamble += "Mezzo-soprano\" "
            elif voice == 3:
                preamble += "Alto\" "
            preamble += "<<\n\\new Voice = \"vocal\" { \\relative c'' { \n\\tempo 4 = "
            tempo = str(self._dodec.tempo)
            preamble += tempo
            preamble += "\n\\set midiInstrument = #\"flute\"\n\\clef \"treble\" \n\\key c \\major\n\\time "
            preamble += str(self._dodec.time_enumerator)
            preamble += "/"
            preamble += str(self._dodec.time_denominator)
            preamble += "\n"
        elif voice == 4:  # G clef octave down
            preamble += "\n\\new Staff = \"Tenor\" <<\n\\new Voice = \"vocal\" { \\relative c' { \n\\tempo 4 = "
            preamble += str(self._dodec.tempo)
            preamble += "\n\\set midiInstrument = #\"clarinet\"\n\\clef \"treble\" \n\\key c \\major\n\\time "
            preamble += str(self._dodec.time_enumerator)
            preamble += "/"
            preamble += str(self._dodec.time_denominator)
            preamble += "\n"
        elif voice in range(5, 7):  # F clef
            preamble += "\n\\new Staff = \""
            if voice == 5:
                preamble += "Baritone\""
            elif voice == 6:
                preamble += "Bass\""
            preamble += " <<\n\\new Voice = \"vocal\" { \\relative f { \n\\tempo 4 = "
            preamble += str(self._dodec.tempo)
            preamble += "\n\\set midiInstrument = #\"piano\"\n\\clef \"bass\" \n\\key c \\major\n\\time "
            preamble += str(self._dodec.time_enumerator)
            preamble += "/"
            preamble += str(self._dodec.time_denominator)
            preamble += "\n"
        return preamble

    def generate_composition(self):
        print("generating composition")
        # For each voice, generate the number of repeats for the series.
        for voice in self._dodec.voices:
            self._composition += self.create_voice_preamble(voice)
            for i in range(self._dodec.repeats):
                # Generate the repeat based on the series and the provided characteristics
                # First, determine the variation of this repeat
                variation = random.randint(0, 3)
                if variation == Variations.SERIES:
                    self._composition += self.generate_repeat(self._dodec.series, voice)
                elif variation == Variations.INVERSE:
                    self._composition += self.generate_repeat(self._dodec.inverse, voice)
                elif variation == Variations.RETROGRADE:
                    self._composition += self.generate_repeat(self._dodec.retrograde, voice)
                else:  # RETROGRADEINVERSE
                    self._composition += self.generate_repeat(self._dodec.retrograde_inverse, voice)
            self._composition += "} }\n>>\n\n"
        self._composition += ">> >> } }\n"

    def generate_score(self):
        """ Generate a composition based on the settings provided. """
        self._score += "\\version \"2.10.33\"\n"
        self._score += "\\header\n{\n"
        self._score += "title = \""
        self._score += self._dodec.title
        self._score += "\"\n"
        self._score += "composer = \"Randomly generated by Dodecaphonist\"\n}\n"
        self._score += "\\score {\n{ \n<<\n"
        self._score += "\\new StaffGroup\n\\relative <<\n"
        self.generate_composition()
        self._score += self._composition
        self._score += "\n\n\\midi { } \n\\layout { }\n}\n"

    def save_lilypond_file(self):
        self._dodec.filename += '.ly'
        path = os.path.join(self._dodec.foldername, self._dodec.filename)
        with open(path, 'w') as f:
            f.write(self._score)

    def save_pdf_file(self):
        print("Saving PDF file")
        os.system('cd ' + self._dodec.foldername)
        os.system('lilypond ' + self._dodec.filename)

    def save_midi_file(self):
        print("Saving midi file")
