import os
import random
import dodecaphony
from enum import Enum


class Variations(Enum):
    SERIES = 0
    INVERSE = 1
    RETROGRADE = 2
    RETROGRADEINVERSE = 3


class ScoreGenerator:
    def __init__(self, dodec: dodecaphony.Dodecaphony):
        self._dodec = dodec
        self._composition = ""
        self._score = ""

    def generate_standard(self):
        print("Generating standard series")
        return ""

    def generate_inverse(self):
        print("Generating inverser series")
        return ""

    def generate_retrograde(self):
        print("Generating retrograde series")
        return ""

    def generate_retrogradeinverse(self):
        print("Generating retrograde inverse")
        return ""

    def create_voice_preamble(self, voice):
        preamble = ""
        if voice in range(1, 4):  # G clef
            preamble += "\n\\new Staff = \""
            if voice == 1:
                preamble += "Soprano\" "
            elif voice == 2:
                preamble += "Mezzo-soprano\" "
            elif voice == 3:
                preamble += "Alto\" "
            preamble += "<<\n\\new Voice = \"vocal\" { \\relative c'' { \n\\tempo 4 = "
            tempo = str(self._dodec.tempo)
            preamble += tempo
            preamble += "\n\\set midiInstrument = #\"flute\"\n\\clef \"treble\" \n\\key c \\major\n\\time "
            preamble += str(self._dodec.time_enumerator)
            preamble += "/"
            preamble += str(self._dodec.time_denominator)
            preamble += "\n"
        elif voice == 4:  # G clef octave down
            preamble += "\n\\new Staff = \"Tenor\" <<\n\\new Voice = \"vocal\" { \\relative c' { \n\\tempo 4 = "
            preamble += str(self._dodec.tempo)
            preamble += "\n\\set midiInstrument = #\"clarinet\"\n\\clef \"treble\" \n\\key c \\major\n\\time "
            preamble += str(self._dodec.time_enumerator)
            preamble += "/"
            preamble += str(self._dodec.time_denominator)
            preamble += "\n"
        elif voice in range(5, 7):  # F clef
            preamble += "\n\\new Staff = \""
            if voice == 5:
                preamble += "Baritone\""
            elif voice == 6:
                preamble += "Bass\""
            preamble += " <<\n\\new Voice = \"vocal\" { \\relative f { \n\\tempo 4 = "
            preamble += str(self._dodec.tempo)
            preamble += "\n\\set midiInstrument = #\"piano\"\n\\clef \"bass\" \n\\key c \\major\n\\time "
            preamble += str(self._dodec.time_enumerator)
            preamble += "/"
            preamble += str(self._dodec.time_denominator)
            preamble += "\n"
        return preamble

    def generate_composition(self):
        print("generating composition")
        # For each voice, generate the number of repeats for the series.
        for voice in self._dodec.voices:
            self._composition += self.create_voice_preamble(voice)
            for i in range(self._dodec.repeats):
                # Generate the repeat based on the series and the provided characteristics
                # First, determine the variation of this repeat
                variation = random.randint(0, 3)
                if variation == Variations.SERIES:
                    self._composition += self.generate_standard()
                elif variation == Variations.INVERSE:
                    self._composition += self.generate_inverse()
                elif variation == Variations.RETROGRADE:
                    self._composition += self.generate_retrograde()
                else:  # RETROGRADEINVERSE
                    self._composition += self.generate_retrogradeinverse()
        self._composition += " } }\n>>"

    def generate_score(self):
        """ Generate a composition based on the settings provided. """
        self._score += "\\version \"2.10.33\"\n"
        self._score += "\\header\n{\n"
        self._score += "title = \""
        self._score += self._dodec.title
        self._score += "\"\n"
        self._score += "composer = \"Randomly generated by Dodecaphonist\"\n}\n"
        self._score += "\\score {\n{ \n<<\n"
        self._score += "\\new StaffGroup\n\\relative <<\n"
        self.generate_composition()
        self._score += self._composition
        self._score += "\n\n>>\n\n>>\n }\n\\midi { } \n\\layout { }\n}\n"

    def save_lilypond_file(self):
        self._dodec.filename += '.ly'
        path = os.path.join(self._dodec.foldername, self._dodec.filename)
        with open(path, 'w') as f:
            f.write(self._score)

    def save_pdf_file(self):
        print("Saving PDF file")
        os.system('cd ' + self._dodec.foldername)
        os.system('lilypond ' + self._dodec.filename)

    def save_midi_file(self):
        print("Saving midi file")
